#!/bin/bash
clear
echo -e "actuel emplacement: $PWD\n"
read -p "Entre le chemin ou l'on trouve t'on .git: " CHEMIN
cd $CHEMIN
echo -e "\n===============> GIT STATUS <===============\n"
if [[ -n `git status | grep add` ]]
then
    git status
    echo -e "\n===============> GIT ADD <===============\n"
    read -p "Entre les fichiers que tu veux add: " FILES
    git add $FILES
    echo -e "\n===============> GIT COMMIT <===============\n"
    read -p "Entre le message que tu veux commit: " MSG
    echo ""
    git commit -m "$MSG"
    echo -e "\n===============> GIT PUSH <===============\n"
    git push
    echo -e "\n===============> GIT STATUS <===============\n"
fi

git status
cd $OLDPWD
